 *	IADLS/ADLS ---------------------------------------------------------------------------------- ;
 	* Coding ADLS ;
	if 1<=daily_living2<=4 then ADL1=daily_living2;
	if 1<=daily_living3<=4 then ADL2=daily_living3;
	if 1<=daily_living4<=4 then ADL3=daily_living4;
	if 1<=daily_living5<=4 then ADL4=daily_living5;
	if 1<=daily_living8<=4 then ADL5=daily_living8;
	if 1<=daily_living9<=4 then ADL6=daily_living9;
	if 1<=daily_living10<=4 then ADL7=daily_living10;
	if 1<=daily_living11<=4 then ADL8=daily_living11;
	if 1<=daily_living12<=4 then ADL9=daily_living12; 
	ADL=sum(ADL1, ADL2, ADL3, ADL4, ADL5, ADL6, ADL7, ADL8, ADL9)/9;
		if cmiss(ADL1, ADL2, ADL3, ADL4, ADL5, ADL6, ADL7, ADL8, ADL9) then ADL=.;
	label ADL='Average ADL measure score, treating [5. Do not do] as missing';
 	* Coding IADLS ;
	if 1<=daily_living1<=4 then IADL1=daily_living1;
	if 1<=daily_living6<=4 then IADL2=daily_living6;
	if 1<=daily_living7<=4 then IADL3=daily_living7;
	IADL=sum(IADL1, IADL2, IADL3)/3;
		if cmiss(IADL1, IADL2, IADL3) then IADL=.;
	label IADL='Average IADL measure score, treating [5. Do not do] as missing';
	* Combined ADL/IADL measure ;
	if 1<=daily_living2<=4  then ADL_IADL_2=daily_living2;
	if 1<=daily_living3<=4  then ADL_IADL_3=daily_living3;
	if 1<=daily_living4<=4  then ADL_IADL_4=daily_living4;
	if 1<=daily_living5<=4  then ADL_IADL_5=daily_living5;
	if 1<=daily_living8<=4  then ADL_IADL_8=daily_living8;
	if 1<=daily_living9<=4  then ADL_IADL_9=daily_living9;
	if 1<=daily_living10<=4 then ADL_IADL_10=daily_living10;
	if 1<=daily_living11<=4 then ADL_IADL_11=daily_living11;
	if 1<=daily_living12<=4 then ADL_IADL_12=daily_living12; 
	if 1<=daily_living1<=4  then ADL_IADL_1=daily_living1;
	if 1<=daily_living6<=4  then ADL_IADL_6=daily_living6;
	if 1<=daily_living7<=4  then ADL_IADL_7=daily_living7;
	ADL_IADL=sum(ADL_IADL_1,ADL_IADL_2,ADL_IADL_3,ADL_IADL_4,ADL_IADL_5,ADL_IADL_6,ADL_IADL_7,
				 ADL_IADL_8,ADL_IADL_9,ADL_IADL_10,ADL_IADL_11,ADL_IADL_12)/12;
		if cmiss(ADL_IADL_1,ADL_IADL_2,ADL_IADL_3,ADL_IADL_4,ADL_IADL_5,ADL_IADL_6,ADL_IADL_7,
				 ADL_IADL_8,ADL_IADL_9,ADL_IADL_10,ADL_IADL_11,ADL_IADL_12)then ADL_IADL=.;
	label ADL_IADL='Average ADL/IADL combined measure score, treating [5. Do not do] as missing';
