	data khandle;
	set  merged.khandle_baseline_kp_20191216; 
/*	PARENT EDUCATION 	*/	
 *	%freq(w1_maternal_education_text*w1_maternal_education w1_paternal_education_text*w1_paternal_education);
	%macro parented (var,parent);
	length educ_&parent._full $ 20;
	* 	MISSING INDICATOR ;
		if W1_&var._EDUCATION=88 or W1_&var._EDUCATION=99 		then educ_&parent._miss=1; else educ_&parent._miss=0; 
	* 	FULL PARENT SPEC ;
		if W1_&var._EDUCATION=88 or W1_&var._EDUCATION=99 		then do; educ_&parent._full_0=1; educ_&parent._full='0. Refused/DK'; 		end; else educ_&parent._full_0=0;
		if W1_&var._EDUCATION=0 and .<W1_&var._EDUCATION_TEXT=<8 	then do; educ_&parent._full_1=1; educ_&parent._full='1. 8th grade or less'; end; else educ_&parent._full_1=0;
		if W1_&var._EDUCATION=0 and 8<W1_&var._EDUCATION_TEXT<12 	then do; educ_&parent._full_2=1; educ_&parent._full='2. HS, no degree'; 	end; else educ_&parent._full_2=0;
		if W1_&var._EDUCATION=0 and W1_&var._EDUCATION_TEXT=12 		then do; educ_&parent._full_3=1; educ_&parent._full='3. HS degree'; 		end; else educ_&parent._full_3=0;
		if 1<=W1_&var._EDUCATION<=5 								then do; educ_&parent._full_4=1; educ_&parent._full='4. Any higher ed'; 	end; else educ_&parent._full_4=0;
	* 	GT HS ;
		if (W1_&var._EDUCATION=0 and W1_&var._EDUCATION_TEXT=12) or 1<=W1_&var._EDUCATION<=5 then educ_&parent._HS=1; else educ_&parent._HS=0;
	* 	LT 8TH GR ;
		if W1_&var._EDUCATION=0 and .<W1_&var._EDUCATION_TEXT<=8 or educ_&parent._miss=1 then educ_&parent._gr8=0; else educ_&parent._gr8=1;
	%mend;
	%parented(maternal,mom); * %freq(educ_mom_miss*w1_maternal_education);
	%parented(paternal,dad); * %freq(educ_dad_gr8*educ_dad_HS*educ_dad_full*w1_paternal_education);
	%macro concordance (cut);
		length educ_parent_&cut. $ 20; 
		if educ_mom_&cut.=1 and educ_dad_&cut.=1 	 then do; educ_parent_&cut._11=1; educ_parent_&cut.="Both high"; end; else educ_parent_&cut._11=0;
			if educ_mom_&cut.=1 and educ_dad_&cut.=0 then do; educ_parent_&cut._10=1; educ_parent_&cut.="Mom high";	 end; else educ_parent_&cut._10=0;
			if educ_mom_&cut.=0 and educ_dad_&cut.=1 then do; educ_parent_&cut._01=1; educ_parent_&cut.="Dad high";  end; else educ_parent_&cut._01=0;
			if educ_mom_&cut.=0 and educ_dad_&cut.=0 then do; educ_parent_&cut._00=1; educ_parent_&cut.="Both low";	 end; else educ_parent_&cut._00=0;
		if educ_mom_&cut.=1 or educ_dad_&cut.=1 then educ_parent_any_&cut._high=1; else educ_parent_any_&cut._high=0;
		if educ_mom_&cut.=0 or educ_dad_&cut.=0 then educ_parent_any_&cut._low=1;  else educ_parent_any_&cut._low =0;
	%mend;
	%concordance(HS); * %freq(educ_parent_HS); * %freq(educ_parent_HS*w1_maternal_education*w1_paternal_education);
	%concordance(gr8);
	run;
