*	Setting weight for single-race ;
	data nonmixed; 
	set khandle;
	where sum(race_white, race_black, race_latino, race_asian)=1;
	if race_nativeam=1 then weight_race=0.5;
		else weight_race=1;
	run;
	/* TEST: proc freq data=nonmixed; table mixed_race*weight_race / list missing; run; */ 

 *	Setting weight for mixed race (two category) --------------------------------------------- ;
	data mixed2_a;
	set khandle(in=a) khandle(in=b);
 *	Creating temporary dummies (otherwise values get written over);
	race_white2=race_white;
	race_black2=race_black;
	race_asian2=race_asian;
	race_latino2=race_latino;
 *	Individual recodes ----------------------------------------------------------------------- ;
 *	Latino and Black/White/Asian ;
	if race_latino2=1 then do;
		if a then do; 	race_latino=1; race_black=0; race_asian=0; race_white=0; end;
		if b then do; 	race_latino=0; 
								if race_black2=1 and race_asian2 ne 1 then do; race_black=1; end; 
								if race_asian2=1 and race_black2 ne 1 then do; race_asian=1; end; 
								if race_white2=1 then race_white=1; end;
		end;
 *	Black and White/Asian ;
	if race_latino2=0 and race_black2=1 then do;
		if a then do; race_black=1; race_asian=0; race_white=0; end;
		if b then do; race_black=0; if race_asian2=1 then race_asian=1; if race_white2=1 then race_white=1; end;
	end;
 *	Asian and White ;
	if race_latino2=0 and race_black2=0 and race_asian2=1 then do;
		if a then do; if race_asian2=1 then race_asian=1; race_white=0; end;
		if b then do; race_asian=0; end;
	end;
	weight_race=0.5;
	where sum(race_white, race_black, race_latino, race_asian)=2 and race_nativeAM ne 1;
	drop race_latino2 race_white2 race_black2 race_asian2;
	proc sort; by studyid;
	run;

 *	Including Native Americans --------------------------------------------------------------- ;
	data mixed2_b;
	set khandle(in=a) khandle(in=b);
 *	Creating temporary dummies (otherwise values get written over);
	race_white2=race_white;
	race_black2=race_black;
	race_asian2=race_asian;
	race_latino2=race_latino;
 *	Individual recodes ----------------------------------------------------------------------- ;
 *	Latino and Black/White/Asian ;
	if race_latino2=1 then do;
		if a then do; 	race_latino=1; race_black=0; race_asian=0; race_white=0; end;
		if b then do; 	race_latino=0; 
								if race_black2=1 and race_asian2 ne 1 then do; race_black=1; end; 
								if race_asian2=1 and race_black2 ne 1 then do; race_asian=1; end; 
								if race_white2=1 then race_white=1; end;
		end;
 *	Black and White/Asian ;
	if race_latino2=0 and race_black2=1 then do;
		if a then do; race_black=1; race_asian=0; race_white=0; end;
		if b then do; race_black=0; if race_asian2=1 then race_asian=1; if race_white2=1 then race_white=1; end;
	end;
 *	Asian and White ;
	if race_latino2=0 and race_black2=0 and race_asian2=1 then do;
		if a then do; if race_asian2=1 then race_asian=1; race_white=0; end;
		if b then do; race_asian=0; end;
	end;
	weight_race=(1/3);
	where sum(race_white, race_black, race_latino, race_asian)=2 and race_nativeAM = 1;
	drop race_latino2 race_white2 race_black2 race_asian2;
	proc sort; by studyid;
	run;
	
	data mixed2; set mixed2_a mixed2_b; run;

	/*	Checks: 
		proc freq data=mixed2; table studyid*mixed_race*race_enrollment*race_white*race_black*race_latino*race_asian*race_nativeam / missing list; run;
		proc print data=mixed2; var studyid last_name race: ethnicity:; where sum(race_white, race_black, race_latino, race_asian)=0; run;
		proc print data=mixed2; var studyid last_name race: ethnicity:; run;
		proc print data=mixed2; var studyid last_name race: ethnicity:; where studyid=201; run;	*/

 *	Setting weight for mixed race (three category) ------------------------------------------- ;
	data mixed3_a;
	set khandle(in=a) khandle(in=b) khandle(in=c);
 *	Creating temporary dummies (otherwise values get written over);
	race_white2=race_white;
	race_black2=race_black;
	race_asian2=race_asian;
	race_latino2=race_latino; 
 *	Individual recodes ----------------------------------------------------------------------- ;
 *	If Latino, White, and Black/Asian (since no one is Latino/Black/Asian, B represents black/Asian difference ;
	if race_latino2=1 then do;
		if a then do; 	race_latino=1; race_black=0; race_asian=0; race_white=0; end;
		if b then do; 	race_latino=0; 
								if race_black2=1 and race_asian2 ne 1 then race_black=1; 
								if race_asian2=1 and race_black2 ne 1 then race_asian=1; 
								race_white=0; end;
		if c then do; 	race_latino=0; race_black=0; race_asian=0; if race_white2=1 then race_white=1; end;
	end;
 *	If Black, Asian, and White (none should be Latino);
	if race_latino2=0 and race_black2=1 then do;
		*test="BLWHAS";
		if a then do; race_black=1; race_asian=0; race_white=0; end;
		if b then do; race_black=0; if race_asian2=1 then race_asian=1; race_white=0; end;
		if c then do; race_black=0; race_asian=0; if race_white2=1 then race_white=1; end;
	end; 
	weight_race=(1/3);
	where sum(race_white, race_black, race_latino, race_asian)=3 and race_nativeAM ne 1;
	drop race_latino2 race_white2 race_black2 race_asian2;
	proc sort; by studyid;
	run;
 *	Including Native Americans --------------------------------------------------------------- ;
	data mixed3_b;
	set khandle(in=a) khandle(in=b) khandle(in=c);
 *	Creating temporary dummies (otherwise values get written over);
	race_white2=race_white;
	race_black2=race_black;
	race_asian2=race_asian;
	race_latino2=race_latino; 
 *	Individual recodes ----------------------------------------------------------------------- ;
 *	If Latino, White, and Black/Asian (since no one is Latino/Black/Asian, B represents black/Asian difference ;
	if race_latino2=1 then do;
		if a then do; 	race_latino=1; race_black=0; race_asian=0; race_white=0; end;
		if b then do; 	race_latino=0; 
								if race_black2=1 and race_asian2 ne 1 then race_black=1; 
								if race_asian2=1 and race_black2 ne 1 then race_asian=1; 
								race_white=0; end;
		if c then do; 	race_latino=0; race_black=0; race_asian=0; if race_white2=1 then race_white=1; end;
	end;
 *	If Black, Asian, and White (none should be Latino);
	if race_latino2=0 and race_black2=1 then do;
		*test="BLWHAS";
		if a then do; race_black=1; race_asian=0; race_white=0; end;
		if b then do; race_black=0; if race_asian2=1 then race_asian=1; race_white=0; end;
		if c then do; race_black=0; race_asian=0; if race_white2=1 then race_white=1; end;
	end; 
	weight_race=(1/4);
	where sum(race_white, race_black, race_latino, race_asian)=3 and race_nativeAM = 1;
	drop race_latino2 race_white2 race_black2 race_asian2;
	proc sort; by studyid;
	run;
